name: Release Builds

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  LIBOQS_VERSION: '0.10.1'
  LIBSODIUM_VERSION: '1.0.20'

jobs:
  build-linux-x86_64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake ninja-build libssl-dev unzip

      - name: Build liboqs static
        run: |
          wget https://github.com/open-quantum-safe/liboqs/archive/refs/tags/${LIBOQS_VERSION}.tar.gz
          tar xzf ${LIBOQS_VERSION}.tar.gz
          cd liboqs-${LIBOQS_VERSION}
          mkdir build && cd build
          cmake -GNinja \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_SHARED_LIBS=OFF \
            -DCMAKE_INSTALL_PREFIX=$HOME/deps \
            -DOQS_BUILD_ONLY_LIB=ON \
            ..
          ninja
          ninja install

      - name: Build libsodium static
        run: |
          wget https://download.libsodium.org/libsodium/releases/libsodium-${LIBSODIUM_VERSION}.tar.gz
          tar xzf libsodium-${LIBSODIUM_VERSION}.tar.gz
          cd libsodium-stable
          ./configure --prefix=$HOME/deps --enable-static --disable-shared
          make -j$(nproc)
          make install

      - name: Install Alire
        run: |
          wget https://github.com/alire-project/alire/releases/download/v2.0.1/alr-2.0.1-bin-x86_64-linux.zip
          unzip alr-2.0.1-bin-x86_64-linux.zip
          chmod +x bin/alr
          echo "$PWD/bin" >> $GITHUB_PATH

      - name: Build ANUBIS-SPARK
        run: |
          export PKG_CONFIG_PATH=$HOME/deps/lib/pkgconfig:$PKG_CONFIG_PATH
          export ANUBIS_LIB_DIR=$HOME/deps/lib
          alr build --release
          strip bin/anubis_main

      - name: Create release archive
        run: |
          mkdir -p release/anubis-spark-linux-x86_64
          cp bin/anubis_main release/anubis-spark-linux-x86_64/
          cp README.md release/anubis-spark-linux-x86_64/
          cp LICENSE-MIT release/anubis-spark-linux-x86_64/
          cp LICENSE-APACHE release/anubis-spark-linux-x86_64/
          cd release
          tar czf anubis-spark-linux-x86_64.tar.gz anubis-spark-linux-x86_64
          sha256sum anubis-spark-linux-x86_64.tar.gz > anubis-spark-linux-x86_64.tar.gz.sha256

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: anubis-spark-linux-x86_64
          path: release/anubis-spark-linux-x86_64.tar.gz*

  build-linux-arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build in ARM64 container
        run: |
          docker run --rm --platform linux/arm64 \
            -v $PWD:/workspace \
            -w /workspace \
            arm64v8/ubuntu:22.04 \
            bash -c "
              apt-get update && \
              apt-get install -y build-essential cmake ninja-build wget libssl-dev unzip && \
              wget https://github.com/open-quantum-safe/liboqs/archive/refs/tags/${LIBOQS_VERSION}.tar.gz && \
              tar xzf ${LIBOQS_VERSION}.tar.gz && \
              cd liboqs-${LIBOQS_VERSION} && \
              mkdir build && cd build && \
              cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=/opt/deps .. && \
              ninja && ninja install && \
              cd /workspace && \
              wget https://download.libsodium.org/libsodium/releases/libsodium-${LIBSODIUM_VERSION}.tar.gz && \
              tar xzf libsodium-${LIBSODIUM_VERSION}.tar.gz && \
              cd libsodium-stable && \
              ./configure --prefix=/opt/deps --enable-static --disable-shared && \
              make -j\$(nproc) && make install && \
              cd /workspace && \
              wget https://github.com/alire-project/alire/releases/download/v2.0.1/alr-2.0.1-bin-aarch64-linux.zip && \
              unzip alr-2.0.1-bin-aarch64-linux.zip && \
              chmod +x bin/alr && \
              export PKG_CONFIG_PATH=/opt/deps/lib/pkgconfig && \
              export ANUBIS_LIB_DIR=/opt/deps/lib && \
              ./bin/alr build --release && \
              strip bin/anubis_main
            "

      - name: Create release archive
        run: |
          mkdir -p release/anubis-spark-linux-arm64
          cp bin/anubis_main release/anubis-spark-linux-arm64/
          cp README.md release/anubis-spark-linux-arm64/
          cp LICENSE-MIT release/anubis-spark-linux-arm64/
          cp LICENSE-APACHE release/anubis-spark-linux-arm64/
          cd release
          tar czf anubis-spark-linux-arm64.tar.gz anubis-spark-linux-arm64
          sha256sum anubis-spark-linux-arm64.tar.gz > anubis-spark-linux-arm64.tar.gz.sha256

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: anubis-spark-linux-arm64
          path: release/anubis-spark-linux-arm64.tar.gz*

  build-macos-x86_64:
    runs-on: macos-13
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies via Homebrew
        run: |
          brew install liboqs libsodium

      - name: Install Alire
        run: |
          wget https://github.com/alire-project/alire/releases/download/v2.0.1/alr-2.0.1-bin-x86_64-macos.zip
          unzip alr-2.0.1-bin-x86_64-macos.zip
          chmod +x bin/alr
          echo "$PWD/bin" >> $GITHUB_PATH

      - name: Build ANUBIS-SPARK
        run: |
          alr build --release
          strip bin/anubis_main

      - name: Create release archive
        run: |
          mkdir -p release/anubis-spark-macos-x86_64
          cp bin/anubis_main release/anubis-spark-macos-x86_64/
          cp README.md release/anubis-spark-macos-x86_64/
          cp LICENSE-MIT release/anubis-spark-macos-x86_64/
          cp LICENSE-APACHE release/anubis-spark-macos-x86_64/
          cd release
          tar czf anubis-spark-macos-x86_64.tar.gz anubis-spark-macos-x86_64
          shasum -a 256 anubis-spark-macos-x86_64.tar.gz > anubis-spark-macos-x86_64.tar.gz.sha256

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: anubis-spark-macos-x86_64
          path: release/anubis-spark-macos-x86_64.tar.gz*

  build-macos-arm64:
    runs-on: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies via Homebrew
        run: |
          brew install liboqs libsodium

      - name: Install Alire
        run: |
          wget https://github.com/alire-project/alire/releases/download/v2.0.1/alr-2.0.1-bin-aarch64-macos.zip
          unzip alr-2.0.1-bin-aarch64-macos.zip
          chmod +x bin/alr
          echo "$PWD/bin" >> $GITHUB_PATH

      - name: Build ANUBIS-SPARK
        run: |
          alr build --release
          strip bin/anubis_main

      - name: Create release archive
        run: |
          mkdir -p release/anubis-spark-macos-arm64
          cp bin/anubis_main release/anubis-spark-macos-arm64/
          cp README.md release/anubis-spark-macos-arm64/
          cp LICENSE-MIT release/anubis-spark-macos-arm64/
          cp LICENSE-APACHE release/anubis-spark-macos-arm64/
          cd release
          tar czf anubis-spark-macos-arm64.tar.gz anubis-spark-macos-arm64
          shasum -a 256 anubis-spark-macos-arm64.tar.gz > anubis-spark-macos-arm64.tar.gz.sha256

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: anubis-spark-macos-arm64
          path: release/anubis-spark-macos-arm64.tar.gz*

  create-release:
    needs: [build-linux-x86_64, build-linux-arm64, build-macos-x86_64, build-macos-arm64]
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            anubis-spark-linux-x86_64/anubis-spark-linux-x86_64.tar.gz
            anubis-spark-linux-x86_64/anubis-spark-linux-x86_64.tar.gz.sha256
            anubis-spark-linux-arm64/anubis-spark-linux-arm64.tar.gz
            anubis-spark-linux-arm64/anubis-spark-linux-arm64.tar.gz.sha256
            anubis-spark-macos-x86_64/anubis-spark-macos-x86_64.tar.gz
            anubis-spark-macos-x86_64/anubis-spark-macos-x86_64.tar.gz.sha256
            anubis-spark-macos-arm64/anubis-spark-macos-arm64.tar.gz
            anubis-spark-macos-arm64/anubis-spark-macos-arm64.tar.gz.sha256
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-docker:
    needs: [build-linux-x86_64, build-linux-arm64]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
